---
title: Calculus I
---

This is the home page for calculus I (MT-101). All assignments, announcements, and other relevant materials will be posted here. 



## Announcements 

<!-- ## Course Assignments
[Assignments](assignments.qmd) -->
<!-- 
## Lectures 
[History](lectures/C0history.qmd)\
[Limits and Continuity](lectures/C0limits.qmd)\
[Download test](notebooks/_test.ipynb){download=""} -->

## Midterm 

The midterm will include everything studied in class up till (and including) section 4.1. 

## Quizzes  

We will most likely have three quizzes. Tentatively:

* Quiz 1 [5 Marks]
* Quiz 2 (10 marks, 8th week)
* Quiz 3 (10 marks, 13th week)\
  + <span style="color:crimson;">December 10 (Tuesday), 6:00pm at LH4, FES </span>
  + <span style="color:crimson;">4.3 to 4.5, 5.1 to 5.6 (as studied in class), 6.1, 6.2</span>   


*N.B.:* If you can't take the quiz for some reason, you need to inform us in advance. 

## Assignments

[Assignment 1](coursematerial/Assignments/MT101Assignment_I.pdf)\
[Assignment 2](coursematerial/Assignments/MT101Assignment_II.pdf)\
[Assignment 3](coursematerial/Assignments/MT101Assignment_III.pdf)\
[Assignment 4](coursematerial/Assignments/MT101Assignment_IV.pdf)\
[Assignment 5](coursematerial/Assignments/MT101Assignment_V.pdf)\

## Slides and Notebooks

Note: You may need to setup python and sympy. You can either see an online tutorial for that, or consult me. 

If you want a quick solution, then you can use sympy on Google colab as shown [here](https://colab.research.google.com/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-5-Sympy.ipynb)


<!-- - [Functions](notebooks/01functions.ipynb) -->
- [Functions](lectures/1functions.qmd)
- [Limits and Continuity](lectures/2limitscontinuity.qmd)

## Course Outline

[Outline (pdf)](coursematerial/MT101%20-%20Course%20Outline%20-%20Fall%202024.pdf)


## Other Resources

### Python related

- [Calculus I in python](https://www.youtube.com/watch?v=-SdIZHPuW9o)



## Contacts

In case of queries regarding attendance, quizzes, and assignments contact:

Mr. Hassan Ali\
Email: hassan.ali@giki.edu.pk

Mr. Aamir Shehzad\
Email: aamir.shehzad@giki.edu.pk

